services:
  db:
    image: postgres:15
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - db

volumes:
  pg_data:
