FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
COPY webpack*.js ./
COPY babel.config.js ./
COPY src ./src

RUN npm ci

RUN npm run build:prod

FROM node:18 AS production

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

COPY --from=builder /app/public/javascripts ./public/javascripts

EXPOSE 3000

CMD ["npm", "start"]