export default {
  container: {
    maxWidth: 1200,
    margin: '2rem auto',
    padding: '2rem',
    background: '#fafafa',
    borderRadius: 8,
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
  },
  title: { marginBottom: '2rem' },
  searchInput: {
    marginBottom: '1rem',
    padding: '0.5rem 1rem',
    borderRadius: 4,
    border: '1px solid #ccc',
    width: '100%',
    maxWidth: 300,
    display: 'block',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    background: '#fff',
    borderRadius: 8,
    overflow: 'hidden',
    boxShadow: '0 1px 4px rgba(0,0,0,0.04)',
  },
  theadRow: { background: '#f5f5f5' },
  th: {
    cursor: 'pointer',
    padding: '0.75rem',
    borderBottom: '2px solid #e0e0e0',
    textAlign: 'left',
    fontWeight: 600,
    fontSize: '1rem',
    color: '#333',
    userSelect: 'none',
  },
  thNoSort: {
    cursor: 'default',
  },
  tbodyRow: {
    textAlign: 'center',
    transition: 'background 0.2s',
  },
  td: {
    padding: '0.75rem',
    borderBottom: '1px solid #eee',
    fontSize: '0.95rem',
    color: '#444',
    verticalAlign: 'middle',
  },
  pagination: {
    marginTop: '1.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '1rem',
  },
  button: {
    padding: '0.5rem 1.25rem',
    borderRadius: 4,
    border: 'none',
    background: '#1976d2',
    color: '#fff',
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: '1rem',
    transition: 'background 0.2s',
  },
  buttonDisabled: {
    background: '#eee',
    color: '#aaa',
    cursor: 'not-allowed',
  },
  pageInfo: { fontSize: '1rem', color: '#555' },
};
