name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH and run deployment script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }} 
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            cd ${{ secrets.DO_TARGET_PATH }}
            echo "NODE_ENV=${{ variables.NODE_ENV }}" > .env
            echo "PORT=${{ variables.PORT }}" >> .env
            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> config/firebase-service-account.json
            docker compose -f docker-compose-prod.yml --env-file .env up --build -d

# Environment Variables & Secrets Required:
# - DO_HOST: IP address or hostname of your DigitalOcean droplet
# - DO_USER: SSH username
# - DO_SSH_KEY: Private SSH key (add as a GitHub secret)
# - DO_PORT: SSH port (default 22)
# - DO_TARGET_PATH: Path on droplet where your repo is located
#
# Add these secrets in your repository settings under Settings > Secrets and variables > Actions
#