name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH and run deployment script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }} 
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            cd ${{ secrets.DO_TARGET_PATH }}
            echo "NODE_ENV=${{ variables.NODE_ENV }}" > .env
            echo "PORT=${{ variables.PORT }}" >> .env
            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
            cat <<EOF > config/firebase-service-account.json
            {
              "type": "${{ secrets.FIREBASE_TYPE }}",
              "project_id": "${{ secrets.FIREBASE_PROJECT_ID }}",
              "private_key_id": "${{ secrets.FIREBASE_PRIVATE_KEY_ID }}",
              "private_key": "${{ secrets.FIREBASE_PRIVATE_KEY }}",
              "client_email": "${{ secrets.FIREBASE_CLIENT_EMAIL }}",
              "client_id": "${{ secrets.FIREBASE_CLIENT_ID }}",
              "auth_uri": "${{ secrets.FIREBASE_AUTH_URI }}",
              "token_uri": "${{ secrets.FIREBASE_TOKEN_URI }}",
              "auth_provider_x509_cert_url": "${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}",
              "client_x509_cert_url": "${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}"
            }
            EOF
            docker compose -f docker-compose-prod.yml --env-file .env up --build -d

# Environment Variables & Secrets Required:
# - DO_HOST: IP address or hostname of your DigitalOcean droplet
# - DO_USER: SSH username
# - DO_SSH_KEY: Private SSH key (add as a GitHub secret)
# - DO_PORT: SSH port (default 22)
# - DO_TARGET_PATH: Path on droplet where your repo is located
#
# Add these secrets in your repository settings under Settings > Secrets and variables > Actions
#